In [1]:
import pandas as pd

In [3]:
original = pd.read_csv('data/songs_reduced.csv')

In [4]:
print(original)

                           id  \
0      6norVbAE14clVMEyDuRw1m
1      1Ddyi4x6R89f9khaD5ESKD
2      129cVllFJHHwSJuW4JnR4F
3      5VBa832DQOkGDFf4lYyo6k
4      2dCZXzWl75dKpdTd2cw4Fd
...                       ...
19995  2swCZgyEIdacDpUNcSQMQI
19996  3odh9wAmeCBuuY5LLSniLs
19997  6ZcsZ7iNQ6S4t1UIV8AyRA
19998  4NiZliLY1laYb6Ewz0RFHu
19999  6vzqZ83ZTSZqnm514WmlGG

                                                    name  \
0                          Luv (sic) pt4 (feat. Shing02)
1                               War Is Hell - Rerecorded
2      Can't We Try (Duet with Collage) - Original Ra...
3                                         I Wear My Life
4                                       Girls in America
...                                                  ...
19995                                            New Day
19996                                     Walk That Walk
19997                                            Beat It
19998                                        Never Again
19999                               When Will I Be Loved

                                     artists  \
0                     ["Nujabes", "Shing02"]
1                          ["T.G. Sheppard"]
2                     ["Rockell", "Collage"]
3                         ["Jo Dee Messina"]
4                       ["Bowling For Soup"]
...                                      ...
19995  ["50 Cent", "Dr. Dre", "Alicia Keys"]
19996                     ["Dorrough Music"]
19997  ["Easy Star All-Stars", "Mykal Rose"]
19998                         ["The Sadies"]
19999                           ["Rockpile"]

                                                  lyrics    genre
0      Snow flakes in January\nHeart warm like Februa...  Hip-Hop
1      It was July, hot in Georgia in 1942\nAll the m...  Country
2      I see your face cloud over like a little girl'...  Hip-Hop
3      Come close, just look at me, can you see\nThat...  Country
4      Girls in America\nGirls in America\nGo!\n\nAno...      Pop
...                                                  ...      ...
19995  It don't take much strength to pull a trigger\...  Hip-Hop
19996  She can\nWalk that walk, walk that walk,\nWalk...  Hip-Hop
19997  They told him, "Don't you ever come around her...     Folk
19998  So many times\nI tried to give you\nWhat you s...  Country
19999  I've been made blue\nI've been lied to\nWhen w...      Pop

[20000 rows x 5 columns]

In [11]:
import re


def preprocess_lyrics(text):
    if pd.isna(text):
        return ""

    text = text.lower()
    text = re.sub(r"\b\w*\d\w*\b", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [12]:
original['lyrics'] = original['lyrics'].apply(preprocess_lyrics)

In [16]:
original["tokens"] = original["lyrics"].str.split()

In [17]:
original[['genre', 'lyrics', 'tokens']]

,genre,lyrics,tokens
0,Hip-Hop,snow flakes in january heart warm like februar...,"[snow, flakes, in, january, heart, warm, like,..."
1,Country,it was july hot in georgia in all the men were...,"[it, was, july, hot, in, georgia, in, all, the..."
2,Hip-Hop,i see your face cloud over like a little girls...,"[i, see, your, face, cloud, over, like, a, lit..."
3,Country,come close just look at me can you see that ne...,"[come, close, just, look, at, me, can, you, se..."
4,Pop,girls in america girls in america go another b...,"[girls, in, america, girls, in, america, go, a..."
...,...,...,...
19995,Hip-Hop,it dont take much strength to pull a trigger b...,"[it, dont, take, much, strength, to, pull, a, ..."
19996,Hip-Hop,she can walk that walk walk that walk walk tha...,"[she, can, walk, that, walk, walk, that, walk,..."
19997,Folk,they told him dont you ever come around here d...,"[they, told, him, dont, you, ever, come, aroun..."
19998,Country,so many times i tried to give you what you sai...,"[so, many, times, i, tried, to, give, you, wha..."
19999,Pop,ive been made blue ive been lied to when will ...,"[ive, been, made, blue, ive, been, lied, to, w..."

In [18]:
vocab = set()

for tokens in original['tokens']:
    vocab.update(tokens)

vocab

{'vaux',
 'strategists',
 'parttime',
 'olonka',
 '죽겠네',
 'use',
 'souless',
 'johnny',
 'employer',
 '成功条件都具备',
 'tys',
 'leaviv',
 'alum',
 'callup',
 'vaccine',
 'elegy',
 'mixup',
 'dorms',
 'bmf',
 '真っ赤なお鼻のトナカイさんは',
 'comehither',
 'macker',
 'againhim',
 'brainwashing',
 'cei',
 'dussé',
 'hovel',
 'halfhipster',
 'goldenbasketwe',
 'sheelahroc',
 'collectin',
 '바뀌어',
 'eochróir',
 'secondguess',
 '말아',
 '포기하고',
 'frarri',
 'desurves',
 'bloggers',
 'rivеr',
 'violin',
 '하나뿐인걸',
 'drag',
 'swallar',
 'gunz',
 'scarfs',
 'pigtails',
 '하나는',
 'serei',
 'choga',
 '創未來',
 'fishbowlwall',
 '발사',
 'artifacts',
 'settles',
 'masturbating',
 'ashtabula',
 'team',
 'luigi',
 'hauler',
 'moulin',
 '떠오르잖아',
 'bbl',
 'insides',
 'yioh',
 'slacking',
 'billyclubbin',
 'sua',
 'dartagnan',
 'scandlous',
 'hoodlum',
 'emoji',
 'rush',
 'overtures',
 'flatlined',
 'slender',
 'phillies',
 'strains',
 'sunniest',
 'weakwilled',
 'questi',
 'scooped',
 '變身把cinderella',
 'licker',
 'jade',
 'lignes',
 'sulfurous',
 'yardie',
 'cul',
 'floatn',
 'ling',
 'doings',
 'promulgating',
 'steppa',
 'intimacies',
 'woken',
 'furthest',
 '자욱해',
 'noa',
 'fruitloop',
 '一有風波及時互呵',
 '하기',
 'microwave',
 'montreaux',
 'emoluments',
 'failed',
 'この手で描けばいいんだよ',
 'tweakin',
 '오는',
 'doubleglock',
 'wynette',
 'bonny',
 'challenge',
 'shredder',
 'jackoflove',
 'sinuses',
 'dualach',
 'empathize',
 '氣氛已經熱到爆燈',
 'hookin',
 '本能で',
 'lights',
 'touchdowns',
 'sieben',
 '人有個牲',
 'smalls',
 'flatflat',
 'bdawg',
 'dadadah',
 'areaching',
 'ownin',
 'forklift',
 '지켜',
 'perkins',
 'yessuh',
 'deeper',
 'arrainment',
 'adeptes',
 'darksome',
 'schoolers',
 '내서',
 '泣き顔におぼれて',
 'romancin',
 'puppy',
 'hotdamn',
 'batra',
 '번번이',
 'peeyew',
 'lоuіѕ',
 'ずっと強いから',
 'dfc',
 'boyd',
 'disrespectfully',
 'soles',
 'espanol',
 '불도록',
 'iration',
 '문제에서',
 'exotics',
 'skrrrt',
 'handball',
 'smilе',
 'beastly',
 '바람대로',
 'cooler',
 'complex',
 'ਲਗ',
 'items',
 'cooing',
 '自分自身を見失わないように',
 'leads',
 'jumpstart',
 'chin',
 '나가길',
 'bombshell',
 'dracula',
 '잔상',
 '믿음',
 'lissen',
 'joplins',
 'muss',
 'jedd',
 'satchmo',
 'sadditty',
 'putonghua',
 'hadda',
 'enamorarme',
 'shotta',
 'dildos',
 'correspondence',
 'condemning',
 'mahal',
 'concussion',
 'ante',
 'wentwent',
 'areare',
 'licketysplickly',
 'antigen',
 'manilow',
 'unouno',
 '지워진',
 'estranged',
 'columbia',
 'bayayyayby',
 'divots',
 'godness',
 'chromer',
 'ov',
 'vets',
 'twig',
 'funkyjunky',
 'raced',
 'peruse',
 'civilcivil',
 'julius',
 'juicy',
 'leeches',
 'wing',
 '흔들리지',
 'skism',
 'sleepyhead',
 'stoneycrook',
 'revo',
 'dueces',
 'रन',
 'gere',
 'cheese처럼',
 'aiye',
 'eccepts',
 'bababump',
 'rakin',
 'leta',
 'lingerine',
 'coagulate',
 'evil',
 'いつだってそこで会えるよ',
 'definitine',
 'parasect',
 '알지만',
 'bima',
 'skydive',
 'suldo',
 'sequinned',
 'longitude',
 'reviewed',
 'crowe',
 'sheeyit',
 'nalty',
 'reinstated',
 '마셔',
 'taught',
 'refrigerators',
 'rausch',
 'repeating',
 'skillful',
 'accomplishing',
 'mañana',
 'financed',
 'icet',
 'því',
 '일어설',
 'brewing',
 'cooyah',
 'leggs',
 'emotionless',
 'pourage',
 'dozin',
 'forerunner',
 'amd',
 'reallife',
 'muckiest',
 'lifted',
 'raoul',
 'scaffolding',
 '쭉',
 '난데',
 'crucifixions',
 'majoring',
 '막히게',
 'appreciated',
 'menial',
 'labna',
 'nanbenu',
 '我才不像你們小心眼兒',
 'parched',
 'robins',
 'regained',
 'undid',
 'adolescant',
 '힌트라도',
 'banged',
 'shockg',
 '不受兔子氣',
 'eternamente',
 'uppers',
 'moisturise',
 '停我的旁邊',
 'blossomed',
 'detah',
 'sarangiran',
 'awcantoraolcom',
 'anybodys',
 'musclin',
 'dining',
 'reflective',
 'hastening',
 'hotdog',
 'salesman',
 '남들처럼',
 '세워놓고',
 'closest',
 'superstitions',
 'daybreak',
 'hohno',
 'adopting',
 'reasoning',
 '떼지',
 'この季节のsuperstar',
 'mbaitear',
 'campground',
 'エナジーがみなぎるショーアップステージ',
 'exterior',
 'frying',
 'wooii',
 'bingo',
 'becks',
 'thenks',
 'この道をただ真っ直ぐ行けば',
 'gmc',
 '친군',
 'dulcentre',
 'wode',
 'tuner',
 'faithfully',
 'murderers',
 'mhisani',
 'mclaren',
 'shotin',
 'remain',
 'delaying',
 'mats',
 'prez',
 'wildeyed',
 'vomiting',
 'privelaged',
 'blissing',
 'weirdo',
 'cosmic',
 'fuckabitch',
 'seax',
 'lancelot',
 'mekhi',
 'chows',
 'tidier',
 'dissociate',
 'eightfoot',
 'youâll',
 'cherrypie',
 'clcok',
 'mera',
 'tounguetied',
 'huntsmen',
 'paddock',
 'dheanfaidh',
 'déja',
 'abiodum',
 'tims',
 'danggudae',
 '不然今天就不能',
 'fugate',
 'jukejoint',
 'suppressing',
 'nie',
 'foreskin',
 'executioners',
 'naldeuli',
 'strollers',
 'awindow',
 'akeekeekee',
 'consistent',
 'draw',
 'xan',
 'honorable',
 '生きる意味は',
 'tickles',
 'facecracklin',
 'pornstar',
 'stoker',
 'cometh',
 'crosses',
 'jama',
 'padspads',
 'bagulho',
 'animus',
 'parnell',
 'yung',
 'carver',
 'cruiser',
 '是否就是',
 'shark',
 'sellout',
 '本気ならば',
 'camalagach',
 'sharpshooter',
 'glad',
 'anecdotes',
 'unrepentantly',
 'defiantly',
 '가빠',
 'resplendents',
 'storenrockin',
 'donks',
 '있으니까',
 'narcissism',
 'escuche',
 'evel',
 'graft',
 'unthought',
 'survey',
 'bounty',
 'pardesi',
 'ebiem',
 'doodoodoodoodoodoodoodoo',
 'ainft',
 'defecate',
 'juiceless',
 'filthiness',
 'ensene',
 'looksie',
 'twercolatin',
 'bumbumbum',
 'southeastcoast',
 'hmmmmh',
 'twodoor',
 'recongnize',
 'stuffs',
 '만들어가는',
 'holborns',
 'saenggakhajima',
 'miscalculate',
 'serious',
 'godcipherlovedivine',
 '논하자면',
 'insert',
 'canines',
 'elbow',
 'asali',
 'yaro',
 'cheffin',
 'fun',
 'girlsso',
 'strawberry',
 'prodigal',
 'walked',
 'cmonnnnn',
 'retains',
 '헤어져야만',
 'transvestite',
 'afghanistan',
 'dragin',
 '素直になれないの',
 'unpatriotic',
 'rudebwoy',
 'dally',
 'scrunchies',
 'emmy',
 'fifi',
 'bananays',
 'berlinetta',
 'bulldoggers',
 'intentions',
 'ravenheart',
 'battlescar',
 'chipset',
 'yaksokddawin',
 '楽しませて',
 'stories',
 'sorrowless',
 'underhanded',
 'lover',
 'eileanan',
 'tamil',
 '운전면허를',
 'newspapers',
 'awash',
 '지쳐가는',
 'violation',
 'branford',
 'blackberrys',
 'bhaint',
 'theyre',
 'downâ',
 '能延續你心跳',
 'jane',
 'sistren',
 'mundo',
 'religious',
 'mintues',
 'writs',
 'rotated',
 'devilish',
 'strugglers',
 'rigour',
 'officialtons',
 'beheaded',
 'haus',
 'withstand',
 'turnstyle',
 'leprous',
 'siesta',
 '思えば',
 'personalize',
 'slangin',
 'cyclone',
 'fostering',
 'venezuela',
 'schein',
 'canda',
 'anyway',
 'astrologist',
 'danga',
 'russ',
 'reel',
 'stakesteak',
 'mentira',
 '여자라',
 '미몽',
 'unconcerned',
 'nuffy',
 'june',
 'andretti',
 'bluebells',
 'lacked',
 'reforms',
 'arriere',
 '늘어나지',
 '해주지',
 'cheat',
 'fetus',
 'loinn',
 'julias',
 'heatin',
 'doopdoodoop',
 '죽었지',
 'northside',
 'elixir',
 'соuld',
 'babyand',
 'exonerate',
 '고맙다라는',
 'drúcht',
 'shitted',
 '환경',
 'landmarks',
 'lait',
 'masks',
 'bitnagehaneungeon',
 'addictive',
 '알아주려고도',
 'since',
 'setll',
 'everybodybody',
 'nutsack',
 'unmarked',
 'chiddy',
 'throughyowindow',
 'belated',
 'resides',
 'height',
 'tyre',
 'clue',
 'rih',
 'assassinatin',
 'spiders',
 'bobbled',
 'tallons',
 'mappelle',
 'tashagay',
 'uhmmmm',
 'don抰',
 'pelico',
 '私の話聞いて欲しい',
 'godfathers',
 'unrequited',
 'changeling',
 'hiyah',
 'cried',
 'debtis',
 'shomo',
 'planking',
 'hispters',
 '옷이',
 'stuy',
 'anagram',
 'chickenshit',
 'sixcylinder',
 'quotin',
 'tasteful',
 'studies',
 'agencies',
 '約束できるかい',
 'slaughterslaughter',
 'penitent',
 '원인은',
 'coldlevel',
 'confidant',
 'disconnected',
 'rogets',
 'acclamation',
 'tatuada',
 '變了轉眼之間',
 'spragga',
 '비유하자면',
 'deliverer',
 'episcopal',
 'afdc',
 'coachella',
 'calorie',
 '아니',
 '無限唏噓惜別天',
 'newsflash',
 '있으면',
 'killbeatz',
 'crooklyn',
 'floodwater',
 'manolo',
 '가리면서',
 'savagery',
 '왜인지',
 '노력충',
 'peach',
 '매일같이',
 'pinpoints',
 'contracted',
 'kangaroo',
 'eloquent',
 'impacts',
 'figuratively',
 'uncadaver',
 'moneybag',
 'bloque',
 'nakhre',
 '피카소',
 'aires',
 'mealladh',
 'tara',
 'pogba',
 'nuckie',
 'mirrored',
 'tushie',
 'tenfour',
 'masha',
 'margareta',
 'tesify',
 '없다고',
 'muzzle',
 'insaaaane',
 'predicaments',
 'according',
 'blackbirds',
 '단언컨대',
 'hydra',
 'bamm',
 'reunion',
 'blurt',
 'astràilia',
 '고통이',
 'screwzoo',
 'package',
 'arroz',
 'hendrickx',
 'rinzel',
 '세계를',
 'ninetyfive',
 'outrage',
 'ribstealin',
 'marshmallow',
 'swiper',
 'reoccurring',
 'rediscover',
 'hooray',
 'artery',
 'nkɔmɔ',
 'transista',
 'flirted',
 '혀는',
 'writhes',
 'matinée',
 'powerless',
 'jum',
 'rices',
 'pp',
 'bаbу',
 'unsteady',
 'imprint',
 '상금은',
 'aiphids',
 'moocho',
 'justaswangin',
 'poca',
 '아침',
 'buttercross',
 'hault',
 'steels',
 'nidavellir',
 'propter',
 'spectators',
 'guc',
 'corns',
 'exams',
 'waged',
 'neukkimi',
 'kindling',
 'namjado',
 'setter',
 'broaches',
 'damaging',
 'mеаn',
 'beguine',
 'intestellar',
 'mesh',
 'dicey',
 'stustustudio',
 'revved',
 'mca',
 'painkillers',
 'moments',
 'slightest',
 'hypochondriac',
 'detour',
 'dingo',
 'ilizwe',
 'shuga',
 'kare',
 'hayvic',
 '이기지',
 'solidify',
 'plainclothes',
 'welch',
 'hollowish',
 'dwelt',
 'tanks',
 'squirtin',
 'scurried',
 'actualize',
 'spritzer',
 'skeltah',
 'powe',
 '天生一對就遇上',
 'widdit',
 'publication',
 'freekey',
 'dirtydirty',
 'herbal',
 '래퍼로',
 'rebuild',
 'mélodie',
 'soundtracks',
 '그리는',
 'lotus',
 'deeps',
 'opie',
 'auspicious',
 'chineke',
 'fussin',
 'play',
 '좋게',
 'proverty',
 'californicated',
 'surṗrised',
 'vérifie',
 'guerrilla',
 'llelo',
 'assniggas',
 'boulevards',
 '인사뿐이니',
 'supersize',
 'tod',
 'cal',
 'swath',
 '신기루',
 '모습에',
 'abandonin',
 'hues',
 'cambió',
 'badgalbamby',
 'zigazag',
 'circling',
 '永遠都不放棄',
 'hooping',
 'peppercorn',
 'butthole',
 'henson',
 'mambura',
 '좋아하는',
 'havens',
 '因为爱惜身体所以我戒掉了烟',
 'murderful',
 'hussle',
 'fumanti',
 'ryda',
 '주잖아',
 'vercy',
 '기회',
 'bcbg',
 'dreadlock',
 'paddled',
 'disarmer',
 'sexy',
 'adventure',
 'undoing',
 'smaoiním',
 'labourless',
 'discouver',
 '울부짖는',
 'pussycat',
 'マジなら',
 'scything',
 'uselessness',
 'dateâ',
 'disdisdisdisco',
 '셔츠',
 'justo',
 'objections',
 'seniority',
 '놀리지마',
 'taggin',
 'silverado',
 'passeth',
 '쳐다보니',
 'ylla',
 'vitton',
 'ada',
 'pouncing',
 '들릴까',
 'evoke',
 'anticipatin',
 'abodance',
 'moneybagg',
 'dizzle',
 'mientras',
 'outoftowners',
 'fnh',
 'ahamlack',
 'straighton',
 'wау',
 'yodel',
 '흥분돼',
 'greedy',
 'built',
 'bebia',
 'nebuchadnezzar',
 'cringed',
 'mystified',
 'okayed',
 'mindhow',
 '於風中散發自然',
 'peppered',
 'grandpad',
 'fullеst',
 '차피',
 'josh',
 'fiending',
 'skankin',
 'durrn',
 'shank',
 'journal',
 'アゲもアシもとられた',
 'jr',
 'debuted',
 '只能用清水來灌溉',
 '함께하고',
 'conmen',
 'movins',
 '腳步開始好似有啲飄浮',
 'teling',
 'jarred',
 'leaner',
 'bleeding',
 'ipad',
 'takaku',
 'fike',
 'ppproper',
 'starflower',
 'ceridwen',
 'escapingunscathed',
 'quququququit',
 'silts',
 'nimm',
 'picadores',
 'kushina',
 'deciple',
 'neared',
 'squaddies',
 'roommates',
 'versaces',
 'sizzle',
 'fleshbound',
 'jekowa',
 'streifen',
 'insecurr',
 'initiate',
 'amiri',
 'arlo',
 'tera',
 'pledging',
 'secondbest',
 'dispatches',
 'macll',
 'bridle',
 'spoken',
 'wump',
 'tommorow',
 '그날처럼',
 'constructive',
 'ginna',
 'mercers',
 'streetwalker',
 '감각을',
 'stallone',
 'arlene',
 'duffels',
 'dunna',
 'agressive',
 'stephen',
 'porschea',
 'jemerson',
 '곳으로',
 'metaphorically',
 'xceptionally',
 'enjoys',
 'trippie',
 'eiye',
 'stea',
 'blasé',
 'netball',
 '뻔뻔해',
 'hunnies',
 'beared',
 '스탯을',
 'sprite',
 'figet',
 'lope',
 'folding',
 'nightside',
 'decision',
 'acussin',
 'hamhaham',
 'kraken',
 'そんな每日は',
 'mikko',
 'dungarees',
 '생각뿐인걸',
 'woyoie',
 'janglin',
 'disappearance',
 'drab',
 'runnie',
 'jobless',
 '無視哭的價值',
 'minuteman',
 'dm에',
 'mex',
 'freezmizer',
 'vagary',
 'rilfe',
 'facades',
 '똑바로',
 'emkiss',
 'silencio',
 'crumbin',
 'cancelled',
 'housen',
 'adrift',
 'peasyhaired',
 '為了找到你',
 'prettypretty',
 'returned',
 'cept',
 '君の',
 'milehigh',
 'eway',
 'chirpin',
 'veggies',
 'soured',
 'rememba',
 '隱性的',
 'benched',
 'worker',
 'bugiady',
 'cabinets',
 'coventry',
 'father',
 '哭不是目的',
 'shortbody',
 'expelling',
 'tetê',
 'odmim',
 'dynamites',
 'abideth',
 ...}

In [19]:
tokens = original['tokens'].explode()

In [ ]:
bow = pd.crosstab(tokens.index, tokens)

tokens,alanis,alannah,alanta,alantië,alaqsa,alarm,alarmed,alarmer,alarmin,alarming,...,albert,alberta,alberts,albion,alborosie,alboums,album,albumet,albums,albuquerque
row_0,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
subset = bow.iloc[:, 1500:1541]
subset

In [27]:
row = bow.iloc[0]
palavras = row[row > 0].index
palavras

Index(['a', 'above', 'always', 'an', 'and', 'answer', 'anxiety', 'apex',
       'april', 'as',
       ...
       'with', 'wonder', 'words', 'wouldnt', 'woven', 'write', 'writing', 'ya',
       'you', 'your'],
      dtype='str', name='tokens', length=251)