In [2]:
from collections import Counter

import pandas as pd

In [3]:
original = pd.read_csv("data/songs_reduced.csv")

In [4]:
import re


def preprocess_lyrics(text):
    if pd.isna(text):
        return ""

    text = text.lower()
    text = re.sub(r"\b\w*\d\w*\b", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [5]:
original['lyrics'] = original['lyrics'].apply(preprocess_lyrics)
original["tokens"] = original["lyrics"].str.split()
original[['genre', 'lyrics', 'tokens']]

,genre,lyrics,tokens
0,Hip-Hop,snow flakes in january heart warm like februar...,"[snow, flakes, in, january, heart, warm, like,..."
1,Country,it was july hot in georgia in all the men were...,"[it, was, july, hot, in, georgia, in, all, the..."
2,Hip-Hop,i see your face cloud over like a little girls...,"[i, see, your, face, cloud, over, like, a, lit..."
3,Country,come close just look at me can you see that ne...,"[come, close, just, look, at, me, can, you, se..."
4,Pop,girls in america girls in america go another b...,"[girls, in, america, girls, in, america, go, a..."
...,...,...,...
19995,Hip-Hop,it dont take much strength to pull a trigger b...,"[it, dont, take, much, strength, to, pull, a, ..."
19996,Hip-Hop,she can walk that walk walk that walk walk tha...,"[she, can, walk, that, walk, walk, that, walk,..."
19997,Folk,they told him dont you ever come around here d...,"[they, told, him, dont, you, ever, come, aroun..."
19998,Country,so many times i tried to give you what you sai...,"[so, many, times, i, tried, to, give, you, wha..."
19999,Pop,ive been made blue ive been lied to when will ...,"[ive, been, made, blue, ive, been, lied, to, w..."

In [ ]:
def get_bow(token_column, n_most_commons: float = 4000) -> pd.DataFrame:
    """
    Gera matriz cujas colunas são as palavras e as linhas representam
    a contagem de palavras nos textos.

    Foi necessário reduzir a quantidade de palavras pegando as n mais comuns,
    por questão de limitação de memória.
    """
    all_tokens = token_column.explode()
    token_counts = Counter(token for token in all_tokens).most_common()
    top_tokens = token_counts[:n_most_commons]
    vocab = {token for token, count in top_tokens}

    filtered_tokens = all_tokens[all_tokens.isin(vocab)]
    bow = pd.crosstab(filtered_tokens.index, pd.Categorical(filtered_tokens, categories=list(vocab)))
    bow = bow.reindex(original.index, fill_value=0)

    return bow

Resultados

In [7]:
bow = get_bow(original['tokens'], 6000)

In [8]:
# Dicionário com frequência de palalvras
print(bow.shape)
bow

(20000, 6000)

col_0,finish,fun,youths,conscience,봐,following,upset,robbed,control,yesterdays,...,jock,mistake,suns,gypsy,flowers,forever,par,shared,otherwise,st
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19996,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19997,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19998,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19999,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Palavras mais comuns
bow.sum(axis=0).sort_values(ascending=False).head(10)

col_0
the    233541
i      191137
you    171971
and    128535
a      124823
to     117862
me      88399
my      84150
in      78492
it      74502
dtype: int64

:

In [ ]:
for k, v in dict(bow.iloc[1,:]).items():
    if v < 5:
        continue
    print(f"{k}: {v}")

print(len(bow.iloc[1,:]))

In [ ]:
for k, v in dict(bow.iloc[1,:]).items():
    if v < 5:
        continue
    print(f"{k}: {v}")

print(len(bow.iloc[1,:]))

old