In [ ]:
import re
from collections import Counter

import nltk
import numpy as np
import pandas as pd
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("averaged_perceptron_tagger_eng")

[nltk_data] Downloading package punkt to /home/arthurpmrs/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /home/arthurpmrs/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/arthurpmrs/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /home/arthurpmrs/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

True

In [45]:
stop_words = set(stopwords.words("english"))
stemmer = PorterStemmer()

In [48]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [50]:
def preprocess_lyrics(text):
    if pd.isna(text):
        return ""

    text = text.lower()
    text = re.sub(r"\b\w*\d\w*\b", "", text)
    text = re.sub(r"[^\w\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()

    tokens = word_tokenize(text)
    stems = [
        stemmer.stem(token)
        for token in tokens
        if token not in stop_words
    ]

    return " ".join(stems)

def get_word_count(text: str) -> dict:
    tokens = text.split()
    return Counter(token for token in tokens).most_common()

In [51]:
df = pd.read_csv("data/songs_reduced.csv")
df["preprocessed_lyrics"] = df["lyrics"].apply(preprocess_lyrics)
texts = df["preprocessed_lyrics"].fillna("")

In [52]:
# Selecionar 5 músicas aleatoriamente
selected_indices = df.sample(5, random_state=42).index

selected = df.loc[selected_indices]

selected[["artists", "name", "preprocessed_lyrics"]]

,artists,name,preprocessed_lyrics
10650,"[""The Strumbellas""]",In This Life,know season aint chang everyday look like rain...
2041,"[""Therion""]",Land of Canaan,noah curs canaan live servant teshub anger sto...
8668,"[""Damian Marley""]",Julie,juli one truli one love best juli break heart ...
1114,"[""The Beatles""]",Norwegian Wood (This Bird Has Flown) - Remaste...,girl say show room isnt good norwegian wood as...
13902,"[""Demons & Wizards""]",Final Warning,doom testifi there danc death pass pump wave b...

In [53]:
count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(texts)
X_count.shape

(20000, 66420)

In [54]:
results_count = []

for idx in selected_indices:
    similarities = cosine_similarity(
        X_count[idx],
        X_count
    ).flatten()

    similarities[idx] = -1

    most_similar_position = similarities.argmax()
    similarity_score = similarities[most_similar_position]

    results_count.append({
        "selected_index": idx,
        "similar_index": most_similar_position,
        "similarity": similarity_score
    })

results_count = pd.DataFrame(results_count)

results_count

   selected_index  similar_index  similarity
0           10650           7011    0.486212
1            2041           8180    0.305823
2            8668          10392    0.524894
3            1114          17919    1.000000
4           13902          13903    0.275174

In [ ]:
for _, row in results_count.iterrows():
    original = df.loc[row["selected_index"]]
    similar = df.loc[row["similar_index"]]

    print(f"Música escolhida: {original['name']} - {original['artists']}")
    print(f"Mais semelhante:  {similar['name']} - {similar['artists']}")
    print(f"Similaridade:     {row['similarity']:.4f}")
    print(" ")
    print(">> Letra da música escolhida")
    print(original['lyrics'][:150].strip(), '...')
    print("\n\n>> Letra da música semelhante")
    print(similar['lyrics'][:150].strip(), '...')
    print("-" * 60)
    print(" ")

Música escolhida: In This Life - ["The Strumbellas"]
Mais semelhante:  Something About You - ["James Carter", "BCS"]
Similaridade:     0.4862

>> Letra da música escolhida
I know the season's ain't been changing
And everyday it looks like rain
But I keep hoping for that sun

The streets are filled with demons
Lord that's ...


>> Letra da música semelhante
There's something about you

You keep my heart in the clouds
All the time
Making it hard for me down here
Not to lose my mind

You make me feel someth ...
------------------------------------------------------------

Música escolhida: Land of Canaan - ["Therion"]
Mais semelhante:  Awesome God / How Great Is Our God - ["Triumphant Quartet"]
Similaridade:     0.3058

>> Letra da música escolhida
Noah cursed Canaan to live as a servant
Teshub was angered and the storm
Was sweeping through the land

Land of Gods of wind and sea
Of purple dawns a ...


>> Letra da música semelhante
Our God is an awesome God
He reigns from Heaven above
With wisdom, power and love,
Our God is an awesome God

Our God is an awesome God
He reigns from ...
------------------------------------------------------------

Música escolhida: Julie - ["Damian Marley"]
Mais semelhante:  One More - ["Jimmy Cliff"]
Similaridade:     0.5249

>> Letra da música escolhida
Julie, you are the one
Truly, the only one I love the best
Julie, why did you break my heart?

Well I saw you in the morning Julie baby
Why did we bre ...


>> Letra da música semelhante
One more, one more, one more, one more
I got one more song I must sing
Ting-a-ling

Freedom ring
I got one more song I must sing
Simple song, so sing ...
------------------------------------------------------------

Música escolhida: Norwegian Wood (This Bird Has Flown) - Remastered 2009 - ["The Beatles"]
Mais semelhante:  Norwegian Wood - ["Waylon Jennings"]
Similaridade:     1.0000

>> Letra da música escolhida
I once had a girl
Or should I say
She once had me
She showed me her room
Isn't it good
Norwegian wood

She asked me to stay and she told me to sit any ...


>> Letra da música semelhante
I once had a girl or should I say she once had me
She showed me her room isn't it good Norwegian Wood
She asked me to stay and she told me to sit anyw ...
------------------------------------------------------------

Música escolhida: Final Warning - ["Demons & Wizards"]
Mais semelhante:  I'm Comin' On Back To You - ["Jackie Wilson"]
Similaridade:     0.2752

>> Letra da música escolhida
Doom's testified
There's dancing
When death is passing by
Pumping waves
The beat's inside you
Be the storm
Let passion guide you

Be prepared, think t ...


>> Letra da música semelhante
AAAAAHAAAA!
A don't a let your pretty head work
Your mans truer than a hold on a her
I've seen some swingin girls around every town
But only you can s ...
------------------------------------------------------------

In [80]:
for _, row in results_count.iterrows():
    original = df.loc[row["selected_index"]][['preprocessed_lyrics']].item()
    similar = df.loc[row["similar_index"]][['preprocessed_lyrics']].item()

    # print(original)
    # print(similar)

    original = get_word_count(original)
    similar = get_word_count(similar)

    print(original)
    print(similar)
    original_words = {word for word, count in original}
    similar_words = {word for word, count in similar}

    intersect = original_words.intersection(similar_words)
    
    print(len(intersect), intersect)
    print(" ")

[('know', 11), ('there', 10), ('someth', 10), ('life', 10), ('oh', 5), ('theyr', 5), ('danc', 5), ('dark', 5), ('night', 3), ('chang', 2), ('look', 2), ('that', 2), ('na', 2), ('still', 2), ('wait', 2), ('us', 2), ('season', 1), ('aint', 1), ('everyday', 1), ('like', 1), ('rain', 1), ('keep', 1), ('hope', 1), ('sun', 1), ('street', 1), ('fill', 1), ('demon', 1), ('lord', 1), ('never', 1), ('gon', 1), ('wan', 1), ('everyon', 1), ('river', 1), ('get', 1), ('low', 1), ('skyscrap', 1), ('cover', 1), ('town', 1), ('work', 1), ('day', 1), ('done', 1), ('peopl', 1), ('dress', 1), ('black', 1), ('car', 1), ('got', 1), ('nowher', 1), ('left', 1), ('run', 1)]
[('someth', 35), ('there', 9), ('make', 5), ('aboooout', 5), ('feel', 4), ('ahh', 2), ('keep', 1), ('heart', 1), ('cloud', 1), ('time', 1), ('hard', 1), ('lose', 1), ('mind', 1), ('cant', 1), ('quit', 1), ('figur', 1), ('realli', 1), ('sort', 1), ('spell', 1), ('hide', 1), ('well', 1), ('your', 1)]
3 {'there', 'keep', 'someth'}

[('el', 9), ('god', 8), ('want', 7), ('land', 6), ('sea', 6), ('your', 6), ('canaan', 4), ('see', 4), ('elyon', 4), ('father', 4), ('abu', 4), ('anath', 4), ('curs', 3), ('rule', 3), ('canaanit', 3), ('sail', 3), ('man', 3), ('baal', 3), ('son', 3), ('shalim', 3), ('purpl', 2), ('great', 2), ('king', 2), ('grape', 2), ('upon', 2), ('seven', 2), ('old', 2), ('make', 2), ('wine', 2), ('founder', 2), ('phoenician', 2), ('sky', 2), ('time', 2), ('astart', 2), ('nake', 2), ('lilli', 2), ('hold', 2), ('serpent', 2), ('baalshamem', 2), ('dagon', 2), ('thunder', 2), ('spearhead', 2), ('qudshu', 2), ('aliyan', 2), ('break', 2), ('ham', 2), ('star', 2), ('steer', 2), ('reach', 2), ('enter', 2), ('noah', 1), ('live', 1), ('servant', 1), ('teshub', 1), ('anger', 1), ('storm', 1), ('sweep', 1), ('wind', 1), ('dawn', 1), ('fertil', 1), ('grow', 1), ('town', 1), ('state', 1), ('punic', 1), ('prais', 1), ('mighti', 1), ('he', 1), ('adami', 1), ('shanima', 1), ('lord', 1), ('heaven', 1), ('giver', 1), ('rain', 1), ('one', 1), ('prevail', 1), ('rais', 1), ('spear', 1), ('silenc', 1), ('men', 1), ('holi', 1), ('virgin', 1), ('bringer', 1), ('peac', 1), ('may', 1), ('ball', 1), ('red', 1), ('hot', 1), ('close', 1), ('khem', 1), ('jordan', 1), ('travel', 1), ('name', 1), ('visit', 1), ('templ', 1), ('ugarit', 1), ('honour', 1), ('cedar', 1), ('tree', 1), ('show', 1), ('path', 1), ('unknown', 1), ('histori', 1), ('guid', 1), ('polar', 1), ('galaxi', 1), ('nectar', 1), ('come', 1), ('night', 1), ('pass', 1), ('gate', 1), ('cours', 1), ('take', 1), ('step', 1), ('arriv', 1), ('go', 1), ('way', 1), ('sphere', 1), ('pantheon', 1)]
[('god', 32), ('awesom', 12), ('great', 10), ('reign', 4), ('heaven', 4), ('wisdom', 4), ('power', 4), ('love', 4), ('sing', 2), ('see', 2), ('sky', 1), ('starless', 1), ('void', 1), ('night', 1), ('spoke', 1), ('dark', 1), ('creat', 1), ('light', 1), ('judgement', 1), ('wrath', 1), ('pour', 1), ('sodom', 1), ('merci', 1), ('grace', 1), ('gave', 1), ('us', 1), ('cross', 1), ('hope', 1), ('quickli', 1), ('forgotten', 1)]
6 {'heaven', 'night', 'sky', 'see', 'great', 'god'}

[('one', 17), ('juli', 14), ('come', 7), ('line', 6), ('truli', 5), ('mind', 5), ('woman', 5), ('love', 4), ('best', 4), ('heart', 4), ('babi', 4), ('im', 4), ('say', 4), ('run', 4), ('away', 4), ('thing', 4), ('deh', 4), ('pon', 4), ('god', 4), ('fu', 4), ('dem', 4), ('work', 4), ('bodi', 4), ('break', 3), ('next', 3), ('well', 2), ('saw', 2), ('morn', 2), ('came', 2), ('back', 2), ('even', 2), ('chang', 2), ('lord', 2), ('jr', 2), ('gong', 2), ('raggamuffin', 2), ('man', 2), ('exercis', 2), ('keep', 2), ('muffin', 2), ('apart', 1), ('see', 1), ('seh', 1), ('favorit', 1), ('spine', 1), ('treat', 1), ('right', 1), ('stand', 1), ('mr', 1), ('kind', 1), ('special', 1), ('dedic', 1), ('girl', 1), ('mine', 1), ('could', 1), ('patsi', 1), ('susi', 1), ('carolin', 1), ('give', 1), ('punch', 1)]
[('one', 47), ('got', 12), ('stori', 4), ('song', 3), ('sing', 3), ('hey', 3), ('till', 3), ('must', 2), ('tell', 2), ('arrow', 2), ('bow', 2), ('go', 2), ('dont', 2), ('im', 2), ('mister', 2), ('get', 2), ('way', 2), ('time', 2), ('live', 2), ('bullet', 2), ('gun', 2), ('run', 2), ('deal', 2), ('done', 2), ('shot', 2), ('tingal', 1), ('freedom', 1), ('ring', 1), ('simpl', 1), ('along', 1), ('mysteri', 1), ('true', 1), ('glori', 1), ('let', 1), ('watch', 1), ('flow', 1), ('target', 1), ('hit', 1), ('babi', 1), ('away', 1), ('want', 1), ('listen', 1), ('say', 1), ('natur', 1), ('lover', 1), ('play', 1), ('anoth', 1), ('day', 1), ('life', 1), ('love', 1), ('give', 1), ('cliff', 1), ('climb', 1), ('cant', 1), ('wont', 1), ('prize', 1), ('surṗris', 1), ('open', 1), ('eye', 1), ('goal', 1), ('straight', 1), ('soul', 1), ('control', 1)]
8 {'babi', 'give', 'say', 'away', 'im', 'run', 'love', 'one'}

[('told', 3), ('isnt', 2), ('good', 2), ('norwegian', 2), ('wood', 2), ('time', 2), ('girl', 1), ('say', 1), ('show', 1), ('room', 1), ('ask', 1), ('stay', 1), ('sit', 1), ('anywher', 1), ('look', 1), ('around', 1), ('notic', 1), ('wasnt', 1), ('chair', 1), ('sat', 1), ('rug', 1), ('bide', 1), ('drink', 1), ('wine', 1), ('talk', 1), ('two', 1), ('said', 1), ('bed', 1), ('work', 1), ('morn', 1), ('start', 1), ('laugh', 1), ('didnt', 1), ('crawl', 1), ('sleep', 1), ('bath', 1), ('awok', 1), ('alon', 1), ('bird', 1), ('flown', 1), ('lit', 1), ('fire', 1)]
[('told', 3), ('isnt', 2), ('good', 2), ('norwegian', 2), ('wood', 2), ('time', 2), ('girl', 1), ('say', 1), ('show', 1), ('room', 1), ('ask', 1), ('stay', 1), ('sit', 1), ('anywher', 1), ('look', 1), ('around', 1), ('notic', 1), ('wasnt', 1), ('chair', 1), ('sat', 1), ('rug', 1), ('bide', 1), ('drink', 1), ('wine', 1), ('talk', 1), ('two', 1), ('said', 1), ('bed', 1), ('work', 1), ('morn', 1), ('start', 1), ('laugh', 1), ('didnt', 1), ('crawl', 1), ('sleep', 1), ('bath', 1), ('awok', 1), ('alon', 1), ('bird', 1), ('flown', 1), ('lit', 1), ('fire', 1)]
42 {'sit', 'said', 'girl', 'fire', 'say', 'two', 'awok', 'laugh', 'stay', 'look', 'start', 'time', 'bide', 'didnt', 'wood', 'anywher', 'ask', 'morn', 'talk', 'around', 'chair', 'sleep', 'show', 'drink', 'notic', 'flown', 'good', 'alon', 'told', 'rug', 'crawl', 'lit', 'room', 'norwegian', 'bath', 'sat', 'bed', 'bird', 'isnt', 'wasnt', 'wine', 'work'}

[('given', 6), ('stormlight', 5), ('storm', 4), ('come', 4), ('let', 3), ('ten', 3), ('im', 3), ('feel', 3), ('danc', 2), ('beat', 2), ('final', 2), ('warn', 2), ('white', 2), ('truthless', 2), ('sacr', 2), ('voidbring', 2), ('hatr', 2), ('corrupt', 2), ('blacken', 2), ('wast', 2), ('shard', 2), ('blade', 2), ('brought', 2), ('sorrow', 2), ('mad', 2), ('ye', 2), ('herald', 2), ('old', 2), ('age', 2), ('grow', 2), ('fast', 2), ('reign', 2), ('anger', 2), ('power', 2), ('doom', 1), ('testifi', 1), ('there', 1), ('death', 1), ('pass', 1), ('pump', 1), ('wave', 1), ('insid', 1), ('passion', 1), ('guid', 1), ('prepar', 1), ('think', 1), ('twice', 1), ('assassin', 1), ('price', 1), ('dress', 1), ('ground', 1), ('step', 1), ('upon', 1), ('suppos', 1), ('ill', 1), ('never', 1), ('ask', 1), ('wont', 1), ('question', 1), ('master', 1), ('wish', 1), ('holi', 1), ('law', 1), ('move', 1), ('goe', 1), ('die', 1), ('plea', 1), ('word', 1), ('light', 1), ('black', 1), ('take', 1), ('sphere', 1), ('breath', 1), ('deepli', 1), ('float', 1), ('pull', 1), ('forc', 1), ('hallway', 1), ('dim', 1), ('short', 1), ('last', 1), ('leak', 1), ('cant', 1), ('hold', 1), ('back', 1), ('releas', 1), ('warmth', 1), ('unleash', 1), ('furi', 1), ('oh', 1), ('see', 1), ('lash', 1), ('turn', 1), ('upsid', 1), ('defin', 1), ('direct', 1), ('anew', 1), ('bound', 1), ('summon', 1), ('count', 1), ('heart', 1)]
[('come', 26), ('im', 14), ('babi', 9), ('dont', 5), ('know', 5), ('that', 4), ('got', 4), ('back', 4), ('ta', 3), ('make', 3), ('oh', 3), ('way', 3), ('na', 3), ('hold', 2), ('girl', 2), ('love', 2), ('thrill', 2), ('gon', 2), ('woman', 2), ('nobodi', 2), ('ele', 2), ('hand', 2), ('aaaaahaaaa', 1), ('let', 1), ('pretti', 1), ('head', 1), ('work', 1), ('man', 1), ('truer', 1), ('ive', 1), ('seen', 1), ('swingin', 1), ('around', 1), ('everi', 1), ('town', 1), ('satisfi', 1), ('hurri', 1), ('littl', 1), ('heard', 1), ('cri', 1), ('said', 1), ('think', 1), ('lie', 1), ('kiss', 1), ('touch', 1), ('whoaaoh', 1), ('need', 1), ('warmth', 1), ('miss', 1), ('tender', 1), ('want', 1), ('feelin', 1), ('low', 1), ('packin', 1), ('bag', 1), ('home', 1), ('soon', 1), ('knock', 1), ('door', 1), ('there', 1), ('bit', 1), ('news', 1), ('ever', 1), ('take', 1), ('place', 1), ('wan', 1), ('thing', 1), ('suitcas', 1), ('ay', 1), ('weeeeee', 1), ('ye', 1), ('right', 1), ('aw', 1), ('look', 1)]
11 {'ye', 'think', 'hold', 'there', 'back', 'take', 'come', 'oh', 'im', 'warmth', 'let'}